print("Введите координаты точки А")
x1, y1 = int(input('x=')), int(input('y='))
print()
print("Введите координаты точки B")
x2, y2 = int(input('x=')), int(input('y='))
l = round(((x2-x1)**2+(y2-y1)**2)**0.5, 2)
print('Расстояние между точками - ', l)